<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="4" total="11" passed="5" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-05-16T22:38:03 EEST" name="TestsCollection" finished-at="2022-05-16T22:38:25 EEST" duration-ms="21911">
    <groups>
    </groups>
    <test started-at="2022-05-16T22:38:03 EEST" name="SmokeTests" finished-at="2022-05-16T22:38:11 EEST" duration-ms="7864">
      <class name="Tests.LoginOut">
        <test-method is-config="true" signature="SetUp()[pri:0, instance:Tests.LoginOut@32502377]" started-at="2022-05-16T22:38:07 EEST" name="SetUp" finished-at="2022-05-16T22:38:10 EEST" duration-ms="2560" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method signature="Logout()[pri:0, instance:Tests.LoginOut@32502377]" started-at="2022-05-16T22:38:10 EEST" name="Logout" finished-at="2022-05-16T22:38:11 EEST" duration-ms="790" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Logout -->
      </class> <!-- Tests.LoginOut -->
      <class name="Tests.CreateNewAccount">
        <test-method is-config="true" signature="SetUp()[pri:0, instance:Tests.CreateNewAccount@ffaa6af]" started-at="2022-05-16T22:38:03 EEST" name="SetUp" finished-at="2022-05-16T22:38:07 EEST" duration-ms="3663" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method signature="CreateNewAcc()[pri:0, instance:Tests.CreateNewAccount@ffaa6af]" started-at="2022-05-16T22:38:07 EEST" name="CreateNewAcc" finished-at="2022-05-16T22:38:07 EEST" duration-ms="774" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateNewAcc -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:Tests.CreateNewAccount@ffaa6af]" started-at="2022-05-16T22:38:11 EEST" name="TearDown" finished-at="2022-05-16T22:38:11 EEST" duration-ms="27" status="FAIL">
          <exception class="org.openqa.selenium.remote.http.ConnectionFailedException">
            <message>
              <![CDATA[Unable to establish websocket connection to http://localhost:59851/devtools/browser/ca05cf2d-c118-4f16-a698-3d25c4560c44
Build info: version: '4.1.1', revision: 'e8fcc2cecf'
System info: host: 'DESKTOP-EPAMBL2', ip: '192.168.1.11', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.2'
Driver info: driver.version: RemoteWebDriver]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.remote.http.ConnectionFailedException: Unable to establish websocket connection to http://localhost:59851/devtools/browser/ca05cf2d-c118-4f16-a698-3d25c4560c44
Build info: version: '4.1.1', revision: 'e8fcc2cecf'
System info: host: 'DESKTOP-EPAMBL2', ip: '192.168.1.11', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.2'
Driver info: driver.version: RemoteWebDriver
at org.openqa.selenium.remote.http.netty.NettyWebSocket.<init>(NettyWebSocket.java:104)
at org.openqa.selenium.remote.http.netty.NettyWebSocket.lambda$create$3(NettyWebSocket.java:137)
at org.openqa.selenium.remote.http.netty.NettyClient.openSocket(NettyClient.java:118)
at org.openqa.selenium.devtools.Connection.<init>(Connection.java:77)
at org.openqa.selenium.firefox.FirefoxDriver.maybeGetDevTools(FirefoxDriver.java:366)
at org.openqa.selenium.remote.RemoteWebDriver.close(RemoteWebDriver.java:425)
at Tests.TestParameters.TearDown(TestParameters.java:36)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:637)
at org.testng.TestRunner.afterRun(TestRunner.java:877)
at org.testng.TestRunner.run(TestRunner.java:599)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.remote.http.ConnectionFailedException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- Tests.CreateNewAccount -->
    </test> <!-- SmokeTests -->
    <test started-at="2022-05-16T22:38:11 EEST" name="RegressionTests" finished-at="2022-05-16T22:38:25 EEST" duration-ms="14013">
      <class name="Tests.LoginOK">
        <test-method is-config="true" signature="SetUp()[pri:0, instance:Tests.LoginOK@7b36aa0c]" started-at="2022-05-16T22:38:11 EEST" name="SetUp" finished-at="2022-05-16T22:38:13 EEST" duration-ms="2096" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method signature="Login()[pri:0, instance:Tests.LoginOK@7b36aa0c]" started-at="2022-05-16T22:38:13 EEST" name="Login" finished-at="2022-05-16T22:38:13 EEST" duration-ms="515" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login -->
        <test-method is-config="true" signature="SetUp()[pri:0, instance:Tests.LoginOK@7b36aa0c]" started-at="2022-05-16T22:38:13 EEST" name="SetUp" finished-at="2022-05-16T22:38:15 EEST" duration-ms="1978" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method signature="LoginF()[pri:0, instance:Tests.LoginOK@7b36aa0c]" started-at="2022-05-16T22:38:15 EEST" name="LoginF" finished-at="2022-05-16T22:38:17 EEST" duration-ms="1437" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Įvestas prisijungimo vardas ir/ arba slaptažodis yra neteisingi] but found [Prisijungimas pavyko!]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Įvestas prisijungimo vardas ir/ arba slaptažodis yra neteisingi] but found [Prisijungimas pavyko!]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at Tests.LoginOK.LoginF(LoginOK.java:39)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginF -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:Tests.LoginOK@7b36aa0c]" started-at="2022-05-16T22:38:25 EEST" name="TearDown" finished-at="2022-05-16T22:38:25 EEST" duration-ms="27" status="FAIL">
          <exception class="org.openqa.selenium.remote.http.ConnectionFailedException">
            <message>
              <![CDATA[Unable to establish websocket connection to http://localhost:58872/devtools/browser/e3c18049-06f1-442e-a3fd-103dc111f823
Build info: version: '4.1.1', revision: 'e8fcc2cecf'
System info: host: 'DESKTOP-EPAMBL2', ip: '192.168.1.11', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.2'
Driver info: driver.version: RemoteWebDriver]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.remote.http.ConnectionFailedException: Unable to establish websocket connection to http://localhost:58872/devtools/browser/e3c18049-06f1-442e-a3fd-103dc111f823
Build info: version: '4.1.1', revision: 'e8fcc2cecf'
System info: host: 'DESKTOP-EPAMBL2', ip: '192.168.1.11', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.2'
Driver info: driver.version: RemoteWebDriver
at org.openqa.selenium.remote.http.netty.NettyWebSocket.<init>(NettyWebSocket.java:104)
at org.openqa.selenium.remote.http.netty.NettyWebSocket.lambda$create$3(NettyWebSocket.java:137)
at org.openqa.selenium.remote.http.netty.NettyClient.openSocket(NettyClient.java:118)
at org.openqa.selenium.devtools.Connection.<init>(Connection.java:77)
at org.openqa.selenium.firefox.FirefoxDriver.maybeGetDevTools(FirefoxDriver.java:366)
at org.openqa.selenium.remote.RemoteWebDriver.close(RemoteWebDriver.java:425)
at Tests.TestParameters.TearDown(TestParameters.java:36)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:637)
at org.testng.TestRunner.afterRun(TestRunner.java:877)
at org.testng.TestRunner.run(TestRunner.java:599)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.remote.http.ConnectionFailedException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- Tests.LoginOK -->
      <class name="Tests.LoginOut">
        <test-method is-config="true" signature="SetUp()[pri:0, instance:Tests.LoginOut@5824a83d]" started-at="2022-05-16T22:38:17 EEST" name="SetUp" finished-at="2022-05-16T22:38:19 EEST" duration-ms="1987" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method signature="Logout()[pri:0, instance:Tests.LoginOut@5824a83d]" started-at="2022-05-16T22:38:19 EEST" name="Logout" finished-at="2022-05-16T22:38:20 EEST" duration-ms="657" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Logout -->
      </class> <!-- Tests.LoginOut -->
      <class name="Tests.CreateNewAccount">
        <test-method is-config="true" signature="SetUp()[pri:0, instance:Tests.CreateNewAccount@18df8434]" started-at="2022-05-16T22:38:20 EEST" name="SetUp" finished-at="2022-05-16T22:38:22 EEST" duration-ms="1983" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method signature="CreateNewAcc()[pri:0, instance:Tests.CreateNewAccount@18df8434]" started-at="2022-05-16T22:38:22 EEST" name="CreateNewAcc" finished-at="2022-05-16T22:38:22 EEST" duration-ms="773" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateNewAcc -->
        <test-method is-config="true" signature="SetUp()[pri:0, instance:Tests.CreateNewAccount@18df8434]" started-at="2022-05-16T22:38:22 EEST" name="SetUp" finished-at="2022-05-16T22:38:24 EEST" duration-ms="1984" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method signature="CreateNewAccF()[pri:0, instance:Tests.CreateNewAccount@18df8434]" started-at="2022-05-16T22:38:24 EEST" name="CreateNewAccF" finished-at="2022-05-16T22:38:25 EEST" duration-ms="564" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Toks vartotojo vardas jau egzistuoja] but found [Registered!]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Toks vartotojo vardas jau egzistuoja] but found [Registered!]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at Tests.CreateNewAccount.CreateNewAccF(CreateNewAccount.java:34)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateNewAccF -->
      </class> <!-- Tests.CreateNewAccount -->
    </test> <!-- RegressionTests -->
  </suite> <!-- TestsCollection -->
</testng-results>
